server:
  port: 9527

jwt:
  secret: ntzvtcNo+hjeo4br7lk5VVYfzxN7fya465deA8+dfqw=

spring:
  main:
    web-application-type: reactive
  data:
    redis:
      host: 182.92.222.10
      port: 6379
      password: 123456
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    nacos:
      discovery: localhost:8848 # 配置nacos地址
    gateway:
      routes:
        - id: cloud-price-consumer #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-price-consumer           #匹配后提供服务的路由地址
          predicates:
            - Path=/test/**            # 断言，路径相匹配的进行路由
          filters:
            - Auth
