server:
  port: 8082

# xxl-job配置项
xxl:
  job:
    admin:
      # 在服务未上线之前需要写本地虚拟机地址，这样才能双向访问
      address: http://192.168.117.134:8088/xxl-job-admin
      accessToken: default_token
      timeout: 60
    executor:
      appname: xxl-job-executor-sample
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

spring:
  application:
    name: cloud-price-provider
  cloud:
    nacos:
      discovery: localhost:8848 # 配置nacos地址
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://101.37.13.81:3306/ah2025?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: db_user
#    password: cxk234411!
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ah2025?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 47.92.230.236
      port: 6379
      password: Ay234411

rocketmq:
  name-server: 47.92.230.236:9876     # rocketMq的nameServer地址
  producer:
    group: prize_group        # 生产者组别
    send-message-timeout: 3000  # 消息发送的超时时间
    retry-times-when-send-async-failed: 2  # 异步消息发送失败重试次数
    max-message-size: 4194304       # 消息的最大长度