server:
  port: 8083

# xxl-job配置项
xxl:
  job:
    admin:
      address: http://192.168.150.101:8088/xxl-job-admin
      # 进行测试
      accessToken: default_token
      timeout: 60
    executor:
      appname: xxl-job-executor-sample
      address:
      ip: 192.168.150.1
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30


spring:
  data:
    redis:
      host: 47.92.230.236
      port: 6379
      password: Ay234411
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  application:
    name: cloud-price-consumer
  cloud:
    nacos:
      discovery: localhost:8848 # 配置nacos地址

rocketmq:
  name-server: 47.92.230.236:9876     # rocketMq的nameServer地址
  producer:   # 消费者组别
    group: price_consumer